version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building the React application...
      - npm run build
  post_build:
    commands:
      - echo Starting the React application server...
      - npm start &
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
