version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Specify the Node.js version
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing artifacts...

artifacts:
  files:
    - '**/*'   # Include all files in the build directory
  base-directory: 'build'  # The directory where the React app is built
  discard-paths: yes       # Discard the file paths in the output

cache:
  paths:
    - 'node_modules/**/*'  # Cache `node_modules` to speed up subsequent builds



